id = "tlc"
name = "Typed Lua"
version = "0.0.1"
authors = ["Iurii Belobeev <marsgpl@gmail.com>"]
description = "Typed Lua support (language server)"
repository = "https://github.com/marsgpl/tlc-zed-extension"
schema_version = 1

[language_servers.tlc]
name = "Typed Lua"
language = "Typed Lua"
